version: 2
jobs:
    build:
        docker:
            - image: byuoitav/build-env:master

        working_directory: /go/src/github.com/byuoitav/ui-configuration

        steps:
            - checkout
            - setup_remote_docker
            - run: make deps
            - run: make docker
